services:
  app:
    build:
      context: .
      target: app
    image: ghcr.io/noagenda/website/app:${APP_TAG:-local}
    platform: linux/x86_64
    restart: unless-stopped
    tty: true
    environment:
      DATABASE_URL: postgresql://no_agenda:ChangeMe@database:5432/no_agenda?serverVersion=18&charset=utf8
    depends_on:
      - database
      - mail
    volumes:
      - ./:/srv/app
      - public_media:/srv/app/public/media
    networks:
      - database
      - php
      - web

  database:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: no_agenda
      POSTGRES_USER: no_agenda
      POSTGRES_PASSWORD: ChangeMe
    ports:
      - "8034:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - database

  mail:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "8035:8025"
    networks:
      - php

  web:
    build:
      context: .
      target: web
    image: ghcr.io/noagenda/website/web:${APP_TAG:-local}
    platform: linux/x86_64
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8033:80"
    volumes:
      - ./:/srv/app
      - ./docker/nginx/app.conf.template:/etc/nginx/templates/app.conf.template
      - public_media:/srv/app/public/media
    networks:
      - web

volumes:
  postgres_data:
  public_media:

networks:
  database:
  php:
  web:
