<?php

declare(strict_types=1);

namespace DoctrineMigrations\Postgresql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261002125903 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'PostgreSQL baseline for the current No Agenda model';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE na_bat_signal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(16) NOT NULL, deployed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE na_episode (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(16) NOT NULL, name VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, published_at DATE NOT NULL, published BOOLEAN NOT NULL, special BOOLEAN NOT NULL, duration INT DEFAULT NULL, recording_uri TEXT NOT NULL, chapters_uri TEXT DEFAULT NULL, chapters_path TEXT DEFAULT NULL, cover_uri TEXT DEFAULT NULL, cover_path TEXT DEFAULT NULL, public_shownotes_uri TEXT DEFAULT NULL, shownotes_uri TEXT DEFAULT NULL, shownotes_path TEXT DEFAULT NULL, transcript_uri TEXT DEFAULT NULL, transcript_path TEXT DEFAULT NULL, crawler_output JSON DEFAULT NULL, last_modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE na_file_download (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, crawling_data VARCHAR(32) NOT NULL, last_modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, initialized_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, episode_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B91C9A76362B62A0 ON na_file_download (episode_id)');
        $this->addSql('CREATE TABLE na_network_site (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, description TEXT NOT NULL, uri VARCHAR(255) NOT NULL, display_uri VARCHAR(255) NOT NULL, author VARCHAR(255) DEFAULT NULL, author_uri VARCHAR(255) DEFAULT NULL, priority INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE na_notification_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, raw_subscription TEXT NOT NULL, type VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE na_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_identifier VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE na_video (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, youtube_etag VARCHAR(255) DEFAULT NULL, last_modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, youtube_id VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE na_file_download ADD CONSTRAINT FK_B91C9A76362B62A0 FOREIGN KEY (episode_id) REFERENCES na_episode (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE na_file_download DROP CONSTRAINT FK_B91C9A76362B62A0');
        $this->addSql('DROP TABLE na_bat_signal');
        $this->addSql('DROP TABLE na_episode');
        $this->addSql('DROP TABLE na_file_download');
        $this->addSql('DROP TABLE na_network_site');
        $this->addSql('DROP TABLE na_notification_subscription');
        $this->addSql('DROP TABLE na_user');
        $this->addSql('DROP TABLE na_video');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
